# NumPy 

[Additional Learning Resources](https://www.w3schools.com/python/numpy/default.asp)

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy. To get started we need to install it!

**Note**: Numpy Installation Instructions

NumPy is already included in your environment! We HIGHLY recommend using our environment as shown in the setup and installation lecture. You are good to go if you are using the course environment!

_____
##### For those not using the provided environment:

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](https://www.scipy.org/install.html)**


**If you run at another local python enviroment. You may want to type the following command to install**

    pip install numpy
_____

## Importing NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

## NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

**Why use Numpy array? Why not just a list?**

There are lot's of reasons to use a Numpy array instead of a "standard" python list object. Our main reasons are:
* Memory Efficiency of Numpy Array vs list
* Easily expands to N-dimensional objects
* Speed of calculations of numpy array
* Broadcasting operations and functions with numpy
* All the data science and machine learning libraries we use are built with Numpy

**Simple Example of what numpy array can do**

In [12]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [13]:
type(my_list)

list

In [14]:
type(my_array)

numpy.ndarray

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays from Objects

### From a Python List

We can create an array by directly converting a list or list of lists:

In [15]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [16]:
np.array(my_list)

array([1, 2, 3])

In [17]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [3]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [4]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [6]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:


### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [30]:
np.random.rand(2)

array([0.06155808, 0.65288237])

In [31]:
np.random.rand(5,5)

array([[0.06325157, 0.11161463, 0.39419472, 0.51936806, 0.77756546],
       [0.43731152, 0.35678664, 0.16989733, 0.23318563, 0.58893758],
       [0.75719012, 0.58123796, 0.56441896, 0.81039303, 0.28732513],
       [0.60142236, 0.09324386, 0.25854789, 0.47942512, 0.21280479],
       [0.84949888, 0.81176735, 0.30816767, 0.91334938, 0.1497552 ]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [44]:
np.random.randint(1,100)

88

In [35]:
np.random.randint(1,100,10)

array([71, 18, 42, 74, 71, 42, 14, 32, 69, 69])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [39]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [50]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [55]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

### Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [58]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [59]:
ranarr.max()

np.int32(43)

In [60]:
ranarr.argmax()

np.int32(3)

In [61]:
ranarr.min()

np.int32(1)

In [62]:
ranarr.argmin()

np.int32(1)

### Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
# Vector
arr.shape

(25,)

In [66]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [67]:
arr.reshape(1,25).shape

(1, 25)

In [68]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [69]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [70]:
arr.dtype

dtype('int32')

In [71]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')